### PR TITLE
[OPENJDK-3046] Turn off Crypto checks by default for now. Tweak JDK21 check to support two different build numbers.

### PR DESCRIPTION
**Pull request by sefroberg**
Set new crypto checks to disable for now. Also changesjdk21 check due to build mismatch between rhel 8 and rhel 9.

### CODE REVIEW

**Comment by judovana** [comment]
Yup. Gave sense. Even if the test fails, the skip string is still cosnidered?

**Review by judovana — APPROVED** [review]

**Comment by sefroberg** [comment]
Hmm, good point. I will try against jdk8 to see what happens s.

**Comment by judovana** [comment]
In case it is not skipped, then just return/exit after the echo.

**Comment by patrikcerbak** [comment]
I was wondering about the same thing as @judovana, otherwise looks good to me.

**Review by patrikcerbak — APPROVED** [review]

**Comment by sefroberg** [comment]
Thank you both. Here is the updated results file when run against jdk 8
Passed 420_runS2iLocaBasic.sh
Passed 600_newUserCheck.sh
Ignored 700_listCryptoAlgorithms.sh
Ignored 701_listCryptoAlgorithmsWithFipsSet.sh
Ignored 702_listCryptoProviders.sh
Ignored 703_listCryptoProvidersWithFipsSet.sh

+ setAlgorithmTestsVars
+ echo '!skipped!' broken right now '!skipped!'
!skipped! broken right now !skipped!
+ exit

**Pull request merged**
